Muda o tipo de categoria de videoclass
TreinaDev/classroom-app pull request #18
Opened 2021-03-31 17:18 UTC by matheusma37

- Muda o tipo de categoria da VideoClass de string para integer
- Atualiza testes antigos
- Atualiza arquivos de suporte
- Adiciona verificação em algumas views para saber se o aluno possui um plano contratado
- Refatora código duplicado
- Refatora código pouco descritivos e métodos com mais de uma responsabilidade
- Atualiza o seeds.rb
- Atualiza a forma como o retorno do token é processado e os testes que fazem uso dele
- Adiciona o uso de sessões para evitar chamadas excessivas ao sistemas de matrículas para recuperar os planos do aluno

2021-03-31 21:58 UTC, joaorsalmeida commented on app/controllers/home_controller.rb
>      current_time = DateTime.now
Vamos usar sempre `Time.zone.now` para garantir que estamos seguindo o horário definido na aplicação. Se não estiver configurado ainda precisamos configurar (vejam na doc de i18n que vocês encontram mais a respeito).

2021-03-31 23:43 UTC, joaorsalmeida commented on db/migrate/20210330130527_change_category_to_be_integer_in_video_classes.rb
> +    change_column :video_classes, :category, :integer
Se vamos mudar pra armazenar o `id`, o atributo pdoeria ser renomeado também para `category_id`, o que acham?

Se eu vejo um atributo `category` vou esperar uma string ou um objeto de outro model como resposta.

2021-03-31 23:43 UTC, joaorsalmeida requested changes
Para melhorar a legibilidade sugeri a mudança de `category` para `category_id`.

De resto me parece tudo ok :)

2021-04-01 15:50 UTC, matheusma37 commented
@joaorsalmeida todas as questões pedidas foram corrigidas e a branch já foi atualizada com a versão mais nova na main

2021-04-02 00:03 UTC, joaorsalmeida approved these changes

2021-04-02 00:04 UTC, merged